# Generated by Django 2.1.3 on 2018-11-16 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.URLField()),
                ('slug', models.SlugField(blank=True, null=True)),
                ('pub_image', models.ImageField(blank=True, null=True, upload_to=None)),
            ],
        ),
    ]
